name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    paths-ignore:
      - 'docs/**'

jobs:
  caches:
    name: Create Caches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity/flappy-bird-microgame
    steps:
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

  tests:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    needs: caches
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity/flappy-bird-microgame
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}

  builds:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: caches
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity/flappy-bird-microgame
        targetPlatform:
          - WebGL

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: build/${{ matrix.targetPlatform }}
          key: Build-${{ matrix.targetPlatform }}
          restore-keys: |
            Build-

      - uses: game-ci/unity-builder@v2
        id: builds
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ${{ matrix.projectPath }}
          buildName: ${{ matrix.targetPlatform }}
          buildsPath: build
          allowDirtyBuild: true

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deploys:
    name: Deploys WebGL to Github Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [tests, builds]
    steps:
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: build/WebGL
          target-folder: docs
